### ISSUE TITLE
ReserveSlot预留位功能BUG

### ISSUE THREAD

**Issue by CN-hurui** [Honkai-Impact-4-Galaxy-Journey/UtilPlugin#40]
### 检查项

- [X] 我确认插件已为最新版，且最新版未修复这一bug。
- [X] 我已在 [Issues 页面](https://github.com/dargoncat/UtilPlugin/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

在预留位人数为较小数值时（如1-2人），减去有预留位的玩家数，计算结果可能为负数
即：
```
public static uint Remain => (UtilPlugin.Instance.Config.Slots - Player.List.Where(p => BadgeDatabase.badges.Find(badge => badge.userid == p.UserId)?.reverseslot == "true").Count());
```
通过检查代码，好像是remain计算结果会为负数导致预留位不生效，需要转换为正整数？

### 重现步骤

将UtilPlugin.Instance.Config.Slots调整为1-2人，同时服务器内存在reserveslot人数大于UtilPlugin.Instance.Config.Slots配置的人数，会出现预留位不生效的问题

**Comment by Sirin3rd** [comment]
这玩意不是bug，服务器内有预留位的人是会优先占用预留位。。。但是加一个配置文件也不是不行

**Comment by CN-hurui** [comment]
但是我发现的就是我把配置人数调到20,22这样预留位就会生效，但是改成2个人就不行...所以我看代码的remain计算结果怀疑是计算为负数的问题...



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月6日(周一) 中午12:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Honkai-Impact-4-Galaxy-Journey/UtilPlugin] ReserveSlot预留位功能BUG (Issue #40)




 
这玩意不是bug，服务器内有预留位的人是会优先占用预留位。。。但是加一个配置文件也不是不行

**Comment by Sirin3rd** [comment]
> 但是我发现的就是我把配置人数调到20,22这样预留位就会生效，但是改成2个人就不行...所以我看代码的remain计算结果怀疑是计算为负数的问题...
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年5月6日(周一) 中午12:01 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Honkai-Impact-4-Galaxy-Journey/UtilPlugin] ReserveSlot预留位功能BUG (Issue #40) 这玩意不是bug，服务器内有预留位的人是会优先占用预留位。。。但是加一个配置文件也不是不行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这东西这么判断：
有玩家加入，判断服务器内是否剩余普通位，如是，则直接结束，如否，判定玩家是否有预留位，如是则允许，如否则拒绝

**Comment by Sirin3rd** [comment]
但是有预留位玩家加入会直接占用预留位而非普通位，相当于现版本给有预留位玩家开了一个单独的列表，服务器内预留位仍然先到先得

**Comment by CN-hurui** [comment]
那目前UtilPlugin.Instance.Config.Slots的数值配置为1-2时不生效的原因是...
又是否有办法优化解决呢

**Comment by Sirin3rd** [comment]
在PR了，还没测试，别急。。。。话说你是哪个服务器的？我们想过去



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月8日(周三) 下午2:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Honkai-Impact-4-Galaxy-Journey/UtilPlugin] ReserveSlot预留位功能BUG (Issue #40)




 
那目前UtilPlugin.Instance.Config.Slots的数值配置为1-2时不生效的原因是...
 又是否有办法优化解决呢

**Comment by Griseo-bh3rd** [comment]
抱歉回复晚了，请先从actions里面下载

**Comment by Griseo-bh3rd** [comment]
@all-contributors please add @CN-hurui for bug
please add @Griseo-bh3rd for code, idea, and maintenance

**Comment by Griseo-bh3rd** [comment]
@all-contributors please add @Griseo-bh3rd for code, idea, and maintenance
