### ISSUE TITLE
使用聊天命令

### ISSUE THREAD

**Issue by Sa3ura** [Honkai-Impact-4-Galaxy-Journey/UtilPlugin#50]
### 检查项

- [X] 我确认插件已为最新版，且最新版未修复这一bug。
- [X] 我已在 [Issues 页面](https://github.com/dargoncat/UtilPlugin/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

使用最新的actions编译
在正常加载插件后使用.c 或 .bc 报错
![QQ_1723275100014](https://github.com/user-attachments/assets/6ca30348-8253-4769-b817-302e0f614fda)
![QQ_1723275135412](https://github.com/user-attachments/assets/7257b017-926e-4229-b48e-4e1b6a6d0e8d)

### 重现步骤

在正常加载插件后使用.c 或 .bc

**Comment by Griseo-bh3rd** [comment]
emmm，如果可以，请帮忙pr，最近都很忙（忙着写邮件给nw）
