### ISSUE TITLE
用JBAPI，享终极人生

### ISSUE THREAD

**Issue by Carl-Frellett** [Honkai-Impact-4-Galaxy-Journey/UtilPlugin#55]
yeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by Griseo-bh3rd** [comment]
???

**Comment by Griseo-bh3rd** [comment]
在其功能足够完善前，不会考虑换用此依赖，同时请不要随意创建无可读性，无意义的issue
至于你建议的这个API，建议commit信息起码能让他人看懂，出一个API使用文档，并且发布为nuget包以易于使用

**Comment by Griseo-bh3rd** [comment]
此issue后续声明见 #66 
不要问我为什么编号直接跳到66了，要感谢我们这位author，让我多删了10个issue
这个issue自然不会删，并且欢迎各位来挖坟（bushi）
![批注 2024-12-13 203050](https://github.com/user-attachments/assets/4ead696d-4f42-4ee9-9cd2-fc62b3d1418f)
